name: build-and-deploy

on:
  push:
    branches: [main]
    paths:
      - 'backend/**'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - id: auth
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - uses: google-github-actions/setup-gcloud@v2

      - name: Build and deploy
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          INSTANCE_CONNECTION_NAME: ${{ secrets.INSTANCE_CONNECTION_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
          DB_NAME: ${{ secrets.DB_NAME }}
        run: |
          gcloud builds submit backend --tag gcr.io/$PROJECT_ID/order-scanner:$GITHUB_SHA
          gcloud run deploy order-scanner             --region europe-west1             --image gcr.io/$PROJECT_ID/order-scanner:$GITHUB_SHA             --platform managed             --allow-unauthenticated             --cpu 1 --memory 512Mi             --max-instances 5             --add-cloudsql-instances $INSTANCE_CONNECTION_NAME             --set-env-vars DB_USER=$DB_USER,DB_PASS=$DB_PASS,DB_NAME=$DB_NAME,INSTANCE_CONNECTION_NAME=$INSTANCE_CONNECTION_NAME
